:nick: Kanzashi
:realname: Kanzashi
:pass: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
:use_tls: true
:servers:
  :ircnet:
    - irc.ircnet.ne.jp
    - 6668
    - ISO-2022-JP
  :FriendChat:
    - irc.friend-chat.jp
    - 6664
    - ISO-2022-JP
  :Freenode:
    - irc.freenode.net
    - 7070
    - utf-8
    - true
:plugins:
  :log:
    :enable: true
    :filename: test.log
